### ISSUE TITLE
how to calculate the ddg?

### ISSUE THREAD

**Issue by ak422** [allydunham/foldx_interface_ddg#1]
Hi, I have a question, after I get the 4 files (Indiv_energies_1n8z_AC.fxout, Interaction_1n8z_AC.fxout, Interface_Residues_1n8z_AC.fxout,Summary_1n8z_AC.fxout) of wild-type and mutant, how to calculate the binding affinity changes?

**Comment by allydunham** [comment]
Those files are the standard FoldX output, so you can get a description of them from the FoldX docs to find where the dG is. To calculate the ddG you subtract wt from mut. The script bin/combine.py does a version of this for you, check the --help for details.
